name: JSON Linter
on:
  push:
    branches: Laboratory_work_4
jobs:
  json_linter_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Start JSON Linter
        run: |
          npm i -g @prantlf/jsonlint
          jsonlint $GITHUB_WORKSPACE/*.json
